name: Check base image

on:
  workflow_dispatch:
  schedule:
    - cron: "29 4 * * *"

permissions:
  contents: read
  packages: write

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger build workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run build.yml --ref "${GITHUB_REF_NAME}"
